import Head from 'next/head'
import Link from 'next/link'
import {loginWithGithub,authStateChanged} from './firebase/client.js'
import styles from '../styles/Home.module.css'
import { useEffect, useState } from 'react'
import useUser from '../Hooks/useUser.js'


export default function Login() {


  // const [user,setUser]=useState({})

  // useEffect(()=>{
  //   authStateChanged(setUser)
  // },[])

  const user=useUser()

  const handleClick=()=>{
    loginWithGithub().then(response=>{
      // let user=response.user
      // setUser({
      //   username:user.displayName,
      //   mail:user.email,
      //   profilePicture:user.photoURL,
      // })
      console.log(response)
    }).catch(err=>{
      console.log('ERR :',err)
    })
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>TWclone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          twClone twClone
        </h1>
        <div>
          <h3>{user?.username}</h3>
          <p>{user?.mail}</p>
          {/* <img src={user?.profilePicture} alt="" height="100px"/> */}
        </div>
    
        <Link href="/Home">Home</Link>
        {
          user?null:<button className={styles.gitHub} onClick={()=>handleClick()}>Login with github</button>
        }
      </main>

    </div>
  )
}
