import Head from 'next/head'
import Link from 'next/link'
import {loginWithGithub} from './firebase/client.js'
import styles from '../styles/Home.module.css'

const handleClick=()=>{
  loginWithGithub().then(user=>{
    console.log('response : ',user)
  }).catch(err=>{
    console.log('ERR :',err)
  })
}

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>TWclone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>
        <Link href="/timeline">Timeline</Link>
        <button className={styles.gitHub} onClick={()=>handleClick()}>Login with github</button>
      </main>

    </div>
  )
}
