import Head from 'next/head'
import Link from 'next/link'
import {loginWithGithub,loginWithGoogle,logOut} from './firebase/client.js'
import styles from '../styles/Login.module.css'
import { useEffect, useState } from 'react'
import useUser from '../Hooks/useUser.js'
import { useRouter } from 'next/router'
import Image from 'next/image'
import homeIcon from '../public/home.svg'
import googleIcon from '../public/google.svg'
export default function Login() {

  const router=useRouter()

  const user=useUser()

  // const handleGitHub=()=>{
  //   loginWithGithub().then(res=>{
  //     router.replace('/Home')
  //   }).catch(err=>{
  //     console.log('ERR :',err)
  //   })
  // }
  const handleGoogle=()=>{
    loginWithGoogle().then(res=>{
      router.replace('Home')
    }).catch(err=>{
      console.log('ERR :',err)
    })
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>TWclone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
           twClone
        </h1>
        <div>
          <h1>{user?.username}</h1>
        </div>
        {
          user?null:
          <div className={styles.google} onClick={()=>handleGoogle()}>
            <div className={styles.g}>
              <Image src={googleIcon}
                    height='35px'
                    width='35px'
                    layout='fixed'                      
              />
            </div>
            <p>Login with Google</p>
          </div>
        }

        <Link href="/Home">
          <button className={styles.button}>
            Home
            {
            <div className={styles.house}>
              <Image src={homeIcon}
                  height='35px'
                  width='35px'
                  layout='fixed'                      
              />
            </div>
            }
          </button>
        </Link>
        <button onClick={()=>{logOut()}} className={styles.button} >Log out</button>
      </main>

    </div>
  )
}
